[package]
name    = "aftershock"
version = "0.0.9"
authors = ["Phobos001"]
edition = "2018"
description = "Software Rendering Graphics API written in pure rust"

[lib]
name = "aftershock"
path = "src/lib.rs"
crate-type = ["lib"]

[dependencies]
lodepng = "3.2.2" # load pngs for Image to Vec<u8>
rgb = "0.8.25" # helps the above

[dev-dependencies]
sdl2 = "0.34.3"
minifb = "0.19.1"