[package]
name    = "aftershock"
version = "0.0.15"
authors = ["Keinan Powers / Phobos001"]
edition = "2018"
catagories = "graphics"
keywords = ["graphics", "rendering", "software-rendering", "gamedev"]
description = "Software Rendering Graphics API written in pure rust"
license = "MIT"
repository = "https://github.com/Phobos001/aftershock"
readme = "README.md"

[lib]
name = "aftershock"
path = "src/lib.rs"
crate-type = ["lib"]

[dependencies]
lodepng = "3.2.2" # load pngs for Image to Vec<u8>
rgb = "0.8.25" # helps the above
rusttype = "0.9.2" # TTF Rendering into Image

[dev-dependencies]
sdl2 = "0.35.0"
minifb = "0.22.0"
framebuffer = "0.3.0"
squares-rng = "0.1.1"

[profile.release]
opt-level = 3
