[package]
name    = "aftershock"
version = "0.0.18"
authors = ["Keinan Powers / Phobos001"]
edition = "2021"
catagories = "graphics"
keywords = ["graphics", "rendering", "software-rendering", "gamedev"]
description = "Software Rendering Graphics API written in pure rust"
license = "MIT"
repository = "https://github.com/Phobos001/aftershock"
readme = "README.md"

[lib]
name = "aftershock"
path = "src/lib.rs"
crate-type = ["lib"]

[dependencies]
lodepng = "3.6.2" # load pngs for Image to Vec<u8>
rgb = "0.8.32" # helps the above
rusttype = "0.9.2" # TTF Rendering into Image
rayon = "1.5.3"
num_cpus = "1.13.1"

[dev-dependencies]
sdl2 = "0.35.2"
minifb = "0.23.0"
device_query = "1.1.1"
framebuffer = "0.3.1"
squares-rng = "0.2.0" # Used in asteroids example

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
