[package]
name    = "aftershock"
version = "0.0.7"
authors = ["Phobos001"]
edition = "2018"

[lib]
name = "aftershock"
path = "lib.rs"
crate-type = ["lib"]

[dependencies]
lodepng = "3.2.2" # load pngs for Image to Vec<u8>
rgb = "0.8.25" # helps the above
rodio = "0.13.0"